# Generated by Django 4.0.6 on 2022-07-14 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('cash', models.FloatField()),
                ('is_vip', models.BooleanField(default=True)),
                ('vip_days', models.IntegerField(default=30)),
                ('cashier', models.ManyToManyField(related_name='cashier', to=settings.AUTH_USER_MODEL)),
                ('kitchen', models.ManyToManyField(related_name='kitchen', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('weiter', models.ManyToManyField(related_name='weiter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
